---
# vars file for awx

v_k3s_version: v1.34.1+k3s1
v_awx_chart_version: 3.2.0
v_certmanager_chart_version: 1.14.5
v_awx_install_path: /opt/k8s
v_global_install_path: /opt/kubeinit
v_argocd_chart_version: 9.1.0
